#!/usr/bin/env python3
import asyncio
from tcp import Servidor
import base64, os
import re
from typing import List

nicknamesPerConnection = dict()
canais = dict()

def getKey(dct,value):
    for key in dct:
        temp = dct[key]
        for i in temp:
            if i == value:
                return key

def validar_nome(nome):
    return re.match(br'^[a-zA-Z][a-zA-Z0-9_-]*$', nome) is not None

def sair(conexao):
    print(conexao, 'conexão fechada')
    conexao.fechar()

def dados_recebidos(conexao, dados):

    if dados == b'':
        nicknamesPerConnection.clear()
        return sair(conexao)

    dados = conexao.dados_residuais + dados

    linhas = dados.split(b'\r\n')

    if not dados.endswith(b'\n'):
        conexao.dados_residuais = linhas[-1]
        linhas = linhas[:-1]
    else:
        conexao.dados_residuais = b''

    '''    
    palavras = (conexao.dados_residuais + dados).split(b'\r\n')

    if not dados.endswith(b'\r\n'):
        conexao.dados_residuais = palavras[-1]
        palavras = palavras[:-1]

    for palavra in palavras:
        if palavra == b'':
            continue

        termo = palavra.split()
    '''
    for linha in linhas:
        if linha == b'':
            continue
        termo = linha.split(b' ')

        if termo[0] == b'PING':
            conexao.s.sendall(b':server PONG server :%s\r\n' % termo[1])

        if termo[0] == b'NICK':         
            flagNicknameAlredyExists = 0

            if validar_nome(termo[1]) == False:
                conexao.s.sendall(b':server 432 * %s :Erroneous nickname\r\n' % termo[1])
            else:
                for key in nicknamesPerConnection.values():
                    temp = key
                    for i in temp:
                        if termo[1].lower() == i:
                            flagNicknameAlredyExists = 1
                            break
                
                if flagNicknameAlredyExists == 0:
                    conexao.set_nick(termo[1].decode('ascii'))          # setta o nick atual
                    conexao.nicknameList.append(termo[1].lower())
                    nicknamesPerConnection[conexao] = conexao.nicknameList
                    conexao.s.sendall(b':server 001 %s :Welcome\r\n' % termo[1].lower())
                    conexao.s.sendall(b':server 422 %s :MOTD File is missing\r\n' % termo[1].lower())
                else:
                    conexao.s.sendall(b':server 433 * %s :Nickname is already in use\r\n' % termo[1].lower())                        

        """ PASSO 6 """
        if termo[0] == b'JOIN':
            """ Verifica se o primeiro caracter do nome do canal é "#" e se o restante do nome é valido
            """
            print("AAAAA")
            canal = termo[1].lower()
            nome_canal = termo[1][1:]

            if (canal[0] != 35) or not (validar_nome(nome_canal)):
                conexao.s.sendall(b':server 403 %s :No such channel\r\n' % nome_canal)
            else:
                if canal not in canais:
                    canais[canal] = [conexao.get_nick()]
                else:
                    canais[canal].append(conexao.get_nick())
                    canais[canal].sort()

                print(canais[canal])
                # TODO: implementar envio de mensagem para outros usuários
                conexao.s.sendall(b':%s JOIN :%s\r\n' % (conexao.get_nick().encode(), nome_canal))

                string_builder = ""
                for i in range(len(canais[canal])):
                    if i == 0:
                        string_builder = b'%s ' % canais[canal][i].encode()
                    elif i == len(canais[canal][i]) - 1:
                        string_builder += b'%s' % canais[canal][i].encode()
                    else:
                        string_builder += b'%s ' % canais[canal][i].encode()
                print("BBBB")
                full_message = b':server 353 %s = %s :%s\r\n' % (conexao.get_nick().encode(), canal, string_builder)

                if len(full_message) > 512:
                    print('CCCCCC')
                    while len(full_message) > 510:
                        temp = string_builder
                        temp.split(" ")
                        full_message =  b':server 353 %s = %s :%s %s %s\r\n' % conexao.get_nick().encode(), canal, temp[0], temp[1], temp[2]
                        conexao.s.sendall(b'%s\r\n' % full_message)
                        string_builder = members_builder(temp[2:])
                        full_message = b':server 353 %s = %s :%s\r\n' % conexao.get_nick().encode(), canal, string_builder
                conexao.s.sendall(b'%s' % full_message)
        '''
        if usuario:
            if usuario == conexao:
                if termo[1] in usuarios.keys():
                    print("TESTE")
                    conexao.s.sendall(b':server 433 %s %s :Nickname is already in use\r\n' % (termo[1], termo[1].upper()))
                elif termo[1] not in usuarios.keys():
                    conexao.s.sendall(b':server 001 %s :Welcome\r\n' % termo[1])
                    print(usuarios)
                    conexao.s.sendall(b':server 422 %s :MOTD File is missing\r\n' % termo[1])
            else:
                if termo[1] == termo[1].upper():
                    conexao.s.sendall(b':server 433 %s %s :Nickname is already in use\r\n' % (termo[1], termo[1].upper()))
                else:
                    conexao.s.sendall(b':server 433 * %s :Nickname is already in use\r\n' % termo[1])
        else:
            if termo[1].upper() in usuarios.keys():
                conexao.s.sendall(b':server 433 * %s :Nickname is already in use\r\n' % termo[1])
            else:
                if validar_nome(termo[1]):
                    if termo[1] in usuarios.keys():
                        
                        conexao.s.sendall(b':server 433 * %s :Nickname is already in use\r\n' % termo[1])
                    else:
                        pass

                    usuarios[termo[1].upper()] = conexao

                    print(usuarios)
                            
                    conexao.s.sendall(b':server 001 %s :Welcome\r\n' % termo[1])
                    conexao.s.sendall(b':server 422 %s :MOTD File is missing\r\n' % termo[1])
                else:
                    conexao.s.sendall(b':server 432 * %s :Erroneous nickname\r\n' % termo[1])
'''
    # print(conexao, dados)

def members_builder(members: List) -> str:
    string_builder = ""
    for i in range(len(members)):
        if i == len(members) - 1:
            string_builder += b'%s' % members[i]
        else:
            string_builder += b'%s ' % members[i]

    return string_builder


def conexao_aceita(conexao):
    print(conexao, 'nova conexão')

    conexao.dados_residuais = b''
    conexao.nicknameList = list()
    conexao.registrar_recebedor(dados_recebidos)


servidor = Servidor(6667)
servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)

asyncio.get_event_loop().run_forever()
 